create table if not exists scheduled_posts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id),
    content text not null,
    platforms text[] not null,
    scheduled_at timestamptz not null,
    status text not null default 'pending'
);
