-- Add reviewer role to profiles
alter table profiles
  add column if not exists role text check (role in ('user','reviewer')) default 'user';

-- Table to store post drafts awaiting review
create table if not exists post_drafts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id),
  content text not null,
  status text not null default 'pending',
  comments jsonb[] default '{}'::jsonb[]
);
